"""
balancebot_rpi_onnx.py — RPi Zero 2W
======================================

Runs the trained PPO balance policy on real hardware at 100Hz.
Reads sensor data from ESP32-S3 over GPIO UART, runs ONNX
inference, and sends motor PWM commands back to ESP32-S3.

═══════════════════════════════════════════════════════════════
PACKAGES TO INSTALL ON RPI (one time):
  pip install onnxruntime pyserial pynput
  numpy is pre-installed on Raspberry Pi OS — do not reinstall

FILES NEEDED IN SAME FOLDER AS THIS SCRIPT:
  policy.onnx          <- generated by export_model_onnx.py
  vecnormalize.json    <- generated by export_model_onnx.py

  Copy from PC:
    scp rpi/policy.onnx rpi/vecnormalize.json pi@<rpi_ip>:~/balancebot/

═══════════════════════════════════════════════════════════════
HOW IT WORKS — FULL PIPELINE:

  Step 1 — UART receive (from ESP32-S3):
    ESP32-S3 sends "pitch,pitch_rate,yaw,yaw_rate\n" every 10ms
    RPi reads one line per control step via pyserial

  Step 2 — VecNormalize (observation normalisation):
    Raw sensor values are normalised using stats from training:
      normalised = clip((obs - mean) / sqrt(var + 1e-8), -10, 10)
    This is critical — the ONNX model was trained on normalised
    observations. Feeding raw values gives wrong actions.
    Stats are loaded from vecnormalize.json.

  Step 3 — ONNX inference:
    Normalised obs shape (1, 4) fed into onnxruntime session.
    CPUExecutionProvider used — RPi has no GPU.
    ONNX Runtime applies graph-level optimisations automatically.
    Output: (actions, values, log_prob) — we use actions only.
    actions shape (2,) — left wheel and right wheel in [-1, 1]

  Step 4 — Action to PWM:
    action [-1, 1] scaled to PWM [-255, 255]:
      pwm = int(action * 255)
    Matches how ESP32 drives L298N.

  Step 5 — Keyboard movement (pitch bias):
    Policy was trained to keep pitch = 0.
    To move forward we add +TILT_BIAS to obs[0] (pitch).
    Policy thinks robot is tilting forward → spins wheels forward.
    Key held    → bias applied instantly
    Key released → bias decays smoothly (DECAY multiplier)
    This is the standard approach for self-balancing robots
    without explicit velocity control training.

  Step 6 — UART send (to ESP32-S3):
    RPi sends "left_pwm,right_pwm\n" every 10ms
    ESP32 applies these to L298N motor driver

═══════════════════════════════════════════════════════════════
UART SETUP ON RPI (one time, requires reboot):

  1. Enable hardware serial:
       sudo raspi-config
         Interface Options -> Serial Port
         "Login shell over serial" -> No
         "Serial hardware enabled" -> Yes

  2. Disable Bluetooth to free /dev/ttyAMA0:
       Add to /boot/config.txt:
         dtoverlay=disable-bt
       Then:
         sudo systemctl disable hciuart
         sudo reboot

  3. Verify serial port exists after reboot:
       ls /dev/ttyAMA0   <- should appear

  If using USB-to-Serial adapter instead:
    Change SERIAL_PORT = "/dev/ttyUSB0"
    No raspi-config or Bluetooth changes needed.

PHYSICAL WIRING:
  RPi GPIO14 (TX, pin 8)  -> ESP32-S3 GPIO44 (RX)
  RPi GPIO15 (RX, pin 10) -> ESP32-S3 GPIO43 (TX)
  RPi GND    (pin 6)      -> ESP32-S3 GND
  Both devices are 3.3V — direct connection, no divider needed.

═══════════════════════════════════════════════════════════════
CONTROLS:
  i = forward       k = backward
  j = turn left     l = turn right
  SPACE = stop      q = quit

TUNING:
  TILT_BIAS  — how much robot tilts for movement (radians)
               increase if barely moves, decrease if falls
  TURN_BIAS  — sharpness of turns
  DECAY      — how quickly robot stops when key released
               0.95 = slow stop (long coast)
               0.80 = fast stop (abrupt)
"""

import os
import sys
import json
import time
import threading
import numpy as np
import serial

try:
    import onnxruntime as ort
except ImportError:
    print("ERROR: onnxruntime not installed.")
    print("Run: pip install onnxruntime")
    sys.exit(1)

try:
    from pynput import keyboard as kb
except ImportError:
    print("pip install pynput")
    sys.exit(1)

# ── Configuration ─────────────────────────────────────────────
SERIAL_PORT    = "/dev/ttyAMA0"
BAUD_RATE      = 115200
ONNX_FILE      = "policy.onnx"
NORM_FILE      = "vecnormalize.json"
CONTROL_HZ     = 100
FALL_ANGLE_DEG = 30.0
TILT_BIAS      = 0.05
TURN_BIAS      = 0.10
DECAY          = 0.90
# ─────────────────────────────────────────────────────────────

# ── Load ONNX model ───────────────────────────────────────────
for f in [ONNX_FILE, NORM_FILE]:
    if not os.path.exists(f):
        print(f"ERROR: {f} not found.")
        print("Run export_model_onnx.py on PC then copy here.")
        sys.exit(1)

print(f"Loading {ONNX_FILE}...")

# CPUExecutionProvider — only option on RPi (no GPU)
sess       = ort.InferenceSession(
    ONNX_FILE,
    providers=["CPUExecutionProvider"]
)
input_name = sess.get_inputs()[0].name
print(f"  Input name : {input_name}")
print(f"  Input shape: {sess.get_inputs()[0].shape}")
print(f"  Outputs    : {[o.name for o in sess.get_outputs()]}")

# ── Load VecNormalize stats ───────────────────────────────────
print(f"\nLoading {NORM_FILE}...")
with open(NORM_FILE, "r") as f:
    stats = json.load(f)

obs_mean = np.array(stats["obs_mean"], dtype=np.float64)
obs_var  = np.array(stats["obs_var"],  dtype=np.float64)
obs_clip = float(stats["obs_clip"])

print(f"  obs_mean : {obs_mean}")
print(f"  obs_var  : {obs_var}")
print(f"  obs_clip : {obs_clip}")
print("ONNX policy loaded.\n")


def normalise(obs):
    """Apply VecNormalize — must match training exactly."""
    n = (obs - obs_mean) / np.sqrt(obs_var + 1e-8)
    return np.clip(n, -obs_clip, obs_clip).astype(np.float32)


def policy_forward(obs_norm):
    """
    Run ONNX inference.
    Input:  normalised obs shape (1, 4)
    Output: action shape (2,) — left and right wheel [-1, 1]
    PPO policy() returns (actions, values, log_prob).
    We only use actions[0].
    """
    obs_batch  = obs_norm.reshape(1, -1)
    outputs    = sess.run(None, {input_name: obs_batch})
    action     = outputs[0].flatten()   # outputs[0] = actions
    return action


def action_to_pwm(action_val):
    return int(np.clip(action_val * 255, -255, 255))


# ── Keyboard controller ───────────────────────────────────────
class Controller:
    def __init__(self):
        self._lock = threading.Lock()
        self.fwd = self.bwd = self.lft = self.rgt = False
        self.quit = False

    def on_press(self, key):
        with self._lock:
            try:
                c = key.char
                if   c == 'i': self.fwd  = True
                elif c == 'k': self.bwd  = True
                elif c == 'j': self.lft  = True
                elif c == 'l': self.rgt  = True
                elif c == 'q': self.quit = True
            except AttributeError:
                if key == kb.Key.space:
                    self.fwd = self.bwd = self.lft = self.rgt = False

    def on_release(self, key):
        with self._lock:
            try:
                c = key.char
                if   c == 'i': self.fwd = False
                elif c == 'k': self.bwd = False
                elif c == 'j': self.lft = False
                elif c == 'l': self.rgt = False
            except AttributeError:
                pass

    def read(self):
        with self._lock:
            return self.fwd, self.bwd, self.lft, self.rgt, self.quit


# ── Serial connection ─────────────────────────────────────────
print(f"Opening {SERIAL_PORT} at {BAUD_RATE}...")
try:
    ser = serial.Serial(SERIAL_PORT, BAUD_RATE,
                        timeout=0.02, write_timeout=0.02)
    time.sleep(2.0)
    ser.reset_input_buffer()
except serial.SerialException as e:
    print(f"ERROR: {e}")
    sys.exit(1)

print("Waiting for ESP32-S3...")
deadline = time.time() + 10.0
while time.time() < deadline:
    line = ser.readline().decode("ascii", errors="ignore").strip()
    if line == "READY":
        print("ESP32-S3 ready.\n")
        break
    if "ERR" in line:
        print(f"ESP32-S3 error: {line}")
        sys.exit(1)
else:
    print("WARNING: No READY — continuing anyway\n")

ctrl     = Controller()
listener = kb.Listener(
    on_press=ctrl.on_press, on_release=ctrl.on_release)
listener.start()

print("=" * 45)
print("  i=forward  k=backward  j=left  l=right")
print("  SPACE=stop  q=quit")
print("=" * 45)
print()

# ── Main control loop ─────────────────────────────────────────
STEP_S     = 1.0 / CONTROL_HZ
step       = 0
pitch_bias = 0.0

try:
    while True:
        t0 = time.time()

        fwd, bwd, lft, rgt, do_quit = ctrl.read()
        if do_quit:
            break

        raw = ser.readline().decode("ascii", errors="ignore").strip()

        if raw and raw.count(',') == 3 and not raw.startswith("ERR"):
            try:
                parts      = raw.split(',')
                pitch      = float(parts[0])
                pitch_rate = float(parts[1])
                yaw        = float(parts[2])
                yaw_rate   = float(parts[3])

                fallen = abs(np.degrees(pitch)) > FALL_ANGLE_DEG

                if not fallen:
                    if   fwd and not bwd: pitch_bias = +TILT_BIAS
                    elif bwd and not fwd: pitch_bias = -TILT_BIAS
                    elif fwd and bwd:     pitch_bias =  0.0
                    else:
                        pitch_bias *= DECAY
                        if abs(pitch_bias) < 0.001:
                            pitch_bias = 0.0

                    if   lft and not rgt: turn = -TURN_BIAS
                    elif rgt and not lft: turn = +TURN_BIAS
                    else:                  turn =  0.0

                    obs = np.array([
                        pitch + pitch_bias,
                        pitch_rate,
                        yaw,
                        yaw_rate
                    ], dtype=np.float64)

                    # Normalise then run ONNX inference
                    obs_norm  = normalise(obs)
                    action    = policy_forward(obs_norm)

                    left_pwm  = action_to_pwm(action[0])
                    right_pwm = action_to_pwm(action[1])

                    if turn != 0.0:
                        left_pwm  = int(np.clip(
                            left_pwm  - turn * 255, -255, 255))
                        right_pwm = int(np.clip(
                            right_pwm + turn * 255, -255, 255))
                else:
                    left_pwm   = 0
                    right_pwm  = 0
                    pitch_bias = 0.0

                ser.write(f"{left_pwm},{right_pwm}\n".encode("ascii"))

                if step % 100 == 0:
                    pd = np.degrees(pitch)
                    if   pitch_bias > 0.005:  s = "▶ FWD"
                    elif pitch_bias < -0.005: s = "◀ BWD"
                    elif turn < 0:            s = "↺ LEFT"
                    elif turn > 0:            s = "RIGHT ↻"
                    elif fallen:              s = "FALLEN"
                    else:                     s = "HOLD"
                    print(f"Step {step:6d} | "
                          f"pitch={pd:+6.1f}° | "
                          f"L={left_pwm:+4d} R={right_pwm:+4d} | "
                          f"{s}")

            except (ValueError, IndexError):
                pass

        step += 1

        elapsed = time.time() - t0
        wait    = STEP_S - elapsed
        if wait > 0:
            time.sleep(wait)

except KeyboardInterrupt:
    print("\nCtrl+C")
finally:
    try:
        ser.write(b"0,0\n")
        time.sleep(0.1)
    except Exception:
        pass
    ser.close()
    listener.stop()
    print("Stopped.")